# This is a basic workflow to help you get started with Actions

name: Non-SMP (GCC+MPI)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: prepare-deps
      run: |
        sudo apt install -y openmpi-bin openmpi-doc libopenmpi-dev
        git clone https://github.com/UIUC-PPL/charm.git

    # Build Charm++
    - name: build-charm++
      run: |
        cd charm
        ./build AMPI-only mpi-linux-x86_64 gcc gfortran --with-production --without-romio -j2 -DCSD_NO_IDLE_TRACING=1 -DCSD_NO_PERIODIC=1

    # Build CharmLite
    - name: prep-charmlite
      run: |
        export CHARM_HOME=$GITHUB_WORKSPACE/charm
        mkdir build
        cd build
        cmake -DCHARMLITE_ENABLE_BENCHMARKS=ON ..
        make -j2

    # Test CharmLite
    - name: test-charmlite
      run: |
        export CHARM_HOME=$GITHUB_WORKSPACE/charm
        cd build/bin
        $CHARM_HOME/bin/charmrun ./pgm_basic_example
        $CHARM_HOME/bin/charmrun ./pgm_basic_example +p2
        $CHARM_HOME/bin/charmrun ./pgm_cbench_benchmark
        $CHARM_HOME/bin/charmrun ./pgm_cbench_benchmark +p2
        $CHARM_HOME/bin/charmrun ./pgm_cdt_example
        $CHARM_HOME/bin/charmrun ./pgm_cdt_example +p2
        $CHARM_HOME/bin/charmrun ./jacobi_example 100 10
        $CHARM_HOME/bin/charmrun ./jacobi_example +p2 100 10
        $CHARM_HOME/bin/charmrun ./pgm_pingpong_benchmark
        $CHARM_HOME/bin/charmrun ./pgm_pingpong_benchmark +p2
